-- Insert Categories
SET IDENTITY_INSERT [dbo].[Categories] ON;

INSERT INTO [dbo].[Categories] ([Id], [Name], [Description], [CreatedAt], [UpdatedAt]) VALUES (1, N'Món Nổi Bật', N'Các món ăn và thức uống nổi bật nhất', GETUTCDATE(), GETUTCDATE());
INSERT INTO [dbo].[Categories] ([Id], [Name], [Description], [CreatedAt], [UpdatedAt]) VALUES (2, N'Instant Milk Tea', N'Trà sữa pha chế nhanh', GETUTCDATE(), GETUTCDATE());
INSERT INTO [dbo].[Categories] ([Id], [Name], [Description], [CreatedAt], [UpdatedAt]) VALUES (3, N'Trà Sữa', N'Các loại trà sữa truyền thống', GETUTCDATE(), GETUTCDATE());
INSERT INTO [dbo].[Categories] ([Id], [Name], [Description], [CreatedAt], [UpdatedAt]) VALUES (4, N'Fresh Fruit Tea', N'Trà trái cây tươi', GETUTCDATE(), GETUTCDATE());
INSERT INTO [dbo].[Categories] ([Id], [Name], [Description], [CreatedAt], [UpdatedAt]) VALUES (5, N'Macchiato Cream Cheese', N'Macchiato và kem phô mai', GETUTCDATE(), GETUTCDATE());
INSERT INTO [dbo].[Categories] ([Id], [Name], [Description], [CreatedAt], [UpdatedAt]) VALUES (6, N'Cà Phê', N'Các loại cà phê đặc biệt', GETUTCDATE(), GETUTCDATE());
INSERT INTO [dbo].[Categories] ([Id], [Name], [Description], [CreatedAt], [UpdatedAt]) VALUES (7, N'Ice Cream', N'Kem các loại', GETUTCDATE(), GETUTCDATE());
INSERT INTO [dbo].[Categories] ([Id], [Name], [Description], [CreatedAt], [UpdatedAt]) VALUES (8, N'Special Menu', N'Menu đặc biệt', GETUTCDATE(), GETUTCDATE());

SET IDENTITY_INSERT [dbo].[Categories] OFF;

-- Insert Products
SET IDENTITY_INSERT [dbo].[Products] ON;

-- Món Nổi Bật
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (1, N'Trà Xanh Chanh Leo Kem Phô Mai', N'Trà xanh thanh mát kết hợp với chanh leo chua ngọt và kem phô mai béo ngậy', 38000, NULL, N'https://tocotocotea.com/wp-content/uploads/2025/04/Trà-xanh-chanh-leo-kem-phô-mai.jpg', 1, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (2, N'Trà Sữa Khoai Môn Đường Hổ', N'Trà sữa khoai môn thơm ngon với đường hổ đặc trưng', 38000, NULL, N'https://tocotocotea.com/wp-content/uploads/2025/04/Trà-sữa-khoai-môn-dường-hổ.jpg', 1, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (3, N'Trà Xanh Đào Chanh Leo', N'Trà xanh kết hợp với đào tươi và chanh leo', 35000, NULL, N'https://tocotocotea.com/wp-content/uploads/2025/04/Trà-xanh-dào-chanh-leo.jpg', 1, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (4, N'Ô Long Sữa Boba Cheese', N'Trà ô long với sữa, boba và kem cheese', 38000, NULL, N'https://tocotocotea.com/wp-content/uploads/2025/03/900x900_Ô-Long-Sữa-Boba-Cheese.jpg', 1, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (5, N'Ô Long Đào Tiên', N'Trà ô long với đào tiên ngọt ngào', 35000, NULL, N'https://tocotocotea.com/wp-content/uploads/2025/03/900x900_Ô-Long-Dào-Tiên.jpg', 1, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (6, N'Thạch Dâu Tây - Strawberry Jelly', N'Thạch dâu tây mát lạnh, ngọt ngào', 35000, 48000, N'https://tocotocotea.com/wp-content/uploads/2025/02/FP-1.jpg', 1, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (7, N'Xanh Sữa Nhài Đào Tiên', N'Trà xanh nhài với sữa và đào tiên', 25000, 34000, N'https://tocotocotea.com/wp-content/uploads/2025/02/900x900-Xanh-Sua-Nhai-Dao-Tien.jpg', 1, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (8, N'Ô Long Dâu Tây', N'Trà ô long với dâu tây tươi', 25000, 38000, N'https://tocotocotea.com/wp-content/uploads/2025/02/900x900-O-Long-Dau-Tay.jpg', 1, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (9, N'Oolong Dâu Tây Kem Phô Mai', N'Oolong dâu tây với kem phô mai béo ngậy', 30000, 38000, N'https://tocotocotea.com/wp-content/uploads/2025/02/900x900-Oolong-Dau-Tay-Kem-Pho-Mai.jpg', 1, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (10, N'Oolong Sữa Hạt Dẻ Hoàng Kim', N'Oolong sữa với hạt dẻ hoàng kim thơm béo', 30000, 38000, N'https://tocotocotea.com/wp-content/uploads/2024/12/Oolong-sua-hat-de-hoang-kim_Tea.png', 1, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (11, N'Combo Rẻ Vô Địch', N'Combo giá rẻ với nhiều lựa chọn', 32000, 41000, N'https://tocotocotea.com/wp-content/uploads/2024/11/Combo-re-vo-dich.png', 1, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (12, N'Combo Cay Xè Xè', N'Combo cay xè với nhiều topping', 36000, 56000, N'https://tocotocotea.com/wp-content/uploads/2024/11/Combo-cay-xe-xe.png', 1, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (13, N'Combo Cay Xè', N'Combo cay xè đặc biệt', 39000, 64000, N'https://tocotocotea.com/wp-content/uploads/2024/11/Combo-cay-xe.png', 1, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (14, N'Bánh Tráng Phơi Sương Sa Tế Muối Tỏi Hành', N'Bánh tráng giòn rụm với sa tế, muối tỏi hành', 19000, NULL, N'https://tocotocotea.com/wp-content/uploads/2024/11/z6050430969470_d657b4b1c0c50e1c6f85fcc1b191148f.jpg', 1, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (15, N'Bánh Tráng Muối Tỏi', N'Bánh tráng muối tỏi thơm ngon', 11000, NULL, N'https://tocotocotea.com/wp-content/uploads/2024/11/z6050430969469_1722270eafff9765ed352960398ac38c.jpg', 1, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (16, N'Hồng Trà Mận Quế Hoa Khổng Lồ', N'Hồng trà mận quế hoa size khổng lồ', 22000, NULL, N'https://tocotocotea.com/wp-content/uploads/2024/11/z6050430969392_bf7c447cf1f9854b92d6c9400bce07b6.jpg', 1, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (17, N'Sữa Tươi Yến Mạch', N'Sữa tươi với yến mạch bổ dưỡng', 30000, 39000, N'https://tocotocotea.com/wp-content/uploads/2024/10/Sua-Tuoi-Yen-Mach.png', 1, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (18, N'Sữa tươi Nếp Cẩm', N'Sữa tươi nếp cẩm thơm béo', 30000, 38000, N'https://tocotocotea.com/wp-content/uploads/2024/10/Sua-Tuoi-Nep-Cam.png', 1, 100, 1);

-- Trà Sữa
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (19, N'Ô Long Đào Lê Tây Bắc', N'Ô long với đào lê Tây Bắc thơm ngọt', 25000, 30000, N'https://tocotocotea.com/wp-content/uploads/2024/08/O-Long-Dao-Le-Tay-Bac.png', 3, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (20, N'Xanh Nhài Lê Tây Bắc', N'Trà xanh nhài với lê Tây Bắc', 25000, 30000, N'https://tocotocotea.com/wp-content/uploads/2024/08/Xanh-Nhai-Le-Tay-Bac.png', 3, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (21, N'Trà Sữa Boba Cheese', N'Trà sữa với boba và kem cheese', 25000, 38000, N'https://tocotocotea.com/wp-content/uploads/2024/08/Tra-Sua-BoBa-Cheese.png', 3, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (22, N'Ô Long Sữa Trân Châu Ngũ Cốc', N'Ô long sữa với trân châu ngũ cốc', 25000, 35000, N'https://tocotocotea.com/wp-content/uploads/2023/11/z4925614515113_5bdf67d7e4b3ee98215ea11da9b303e9.jpg', 3, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (23, N'Trà Sữa Trân Châu Đường Hổ', N'Trà sữa trân châu với đường hổ đặc biệt', 25000, 33000, N'https://tocotocotea.com/wp-content/uploads/2023/04/tra-sua-tran-chau-duong-den.jpg', 3, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (24, N'Trà Sữa Phô Mai Tươi', N'Trà sữa với phô mai tươi béo ngậy', 25000, 40000, N'https://tocotocotea.com/wp-content/uploads/2023/01/Tra-sua-pho-mai-tuoi.png', 3, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (25, N'Tiger Sugar', N'Trà sữa tiger sugar đặc trưng', 25000, NULL, N'https://tocotocotea.com/wp-content/uploads/2021/06/TS_TIGER_SUGAR.jpg', 3, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (26, N'Trà Sữa Trân Châu Hoàng Gia', N'Trà sữa trân châu hoàng gia cao cấp', 25000, 38000, N'https://tocotocotea.com/wp-content/uploads/2021/01/Tra-Sua-Tran-Chau-Hoang-Gia-1-copy.jpg', 3, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (27, N'Trà Sữa Ba Anh Em', N'Trà sữa ba anh em đặc biệt', 25000, 39000, N'https://tocotocotea.com/wp-content/uploads/2025/04/3-anh-em.jpg', 3, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (28, N'Trà Sữa Trân Châu Sợi', N'Trà sữa với trân châu sợi đặc biệt', 25000, 39000, N'https://tocotocotea.com/wp-content/uploads/2021/01/tra-sua-tran-chau-soi.jpg', 3, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (29, N'Trà Sữa Kim Cương Đen Okinawa', N'Trà sữa kim cương đen Okinawa', 25000, 38000, N'https://tocotocotea.com/wp-content/uploads/2021/01/Tra-Sua-Okinawa_Moi.png', 3, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (30, N'Trà Sữa Socola', N'Trà sữa vị socola đậm đà', 25000, 35000, N'https://tocotocotea.com/wp-content/uploads/2021/01/Tra-Sua-Socola-1-copy.jpg', 3, 100, 1);

-- Macchiato Cream Cheese
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (31, N'Ô Long Đào Quế Hoa Kem Cheese', N'Ô long đào quế hoa với kem cheese', 30000, 38000, N'https://tocotocotea.com/wp-content/uploads/2024/04/Oolong-Dao-Que-Hoa-Kem-Cheese.png', 5, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (32, N'Phê Sữa Kem Cheese', N'Phê sữa với kem cheese béo ngậy', 30000, 38000, N'https://tocotocotea.com/wp-content/uploads/2024/04/phe-sua-kem-cheese.png', 5, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (33, N'Ô Long Sữa Kem Café Trân Châu Sợi', N'Ô long sữa kem café với trân châu sợi', 30000, 38000, N'https://tocotocotea.com/wp-content/uploads/2024/04/O-long-sua-kem-cafe-tran-chau-soi.png', 5, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (34, N'Ô Long Mận Kem Phô Mai', N'Ô long mận với kem phô mai', 25000, 38000, N'https://tocotocotea.com/wp-content/uploads/2023/05/O-Long-Man-Kem-Pho-Mai.jpg', 5, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (35, N'Ô Long Kem Phô Mai', N'Ô long với kem phô mai classic', 25000, 40000, N'https://tocotocotea.com/wp-content/uploads/2021/01/oolong-kem-pho-mai_75e8d3f11fb3402196416da77c8ff33a_grande.png', 5, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (36, N'Dâu Tằm Kem Phô Mai', N'Dâu tằm với kem phô mai', 30000, 38000, N'https://tocotocotea.com/wp-content/uploads/2021/01/dau-tam-kem-pho-mai.png', 5, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (37, N'Hồng Trà Kem Phô Mai', N'Hồng trà với kem phô mai', 25000, 38000, N'https://tocotocotea.com/wp-content/uploads/2021/01/Hong-Tra-Kem-Pho-Mai-2-copy.jpg', 5, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (38, N'Trà Xanh Kem Phô Mai', N'Trà xanh với kem phô mai', 25000, 38000, N'https://tocotocotea.com/wp-content/uploads/2021/01/Tra-Xanh-Kem-Pho-Mai-2-copy.jpg', 5, 100, 1);

-- Cà Phê
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (39, N'Jelly Milk Coffee', N'Cà phê sữa với thạch thơm ngon', 25000, 38000, N'https://tocotocotea.com/wp-content/uploads/2021/11/Jelly-coffee.jpg', 6, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (40, N'Cheese Milk Coffee', N'Cà phê sữa với kem cheese', 25000, 38000, N'https://tocotocotea.com/wp-content/uploads/2021/11/cheese-milk-coffee.png', 6, 100, 1);

-- Ice Cream
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (41, N'Kem Vani Trà Sữa Trân Châu Hoàng Kim', N'Kem vani trà sữa với trân châu hoàng kim', 25000, NULL, N'https://tocotocotea.com/wp-content/uploads/2024/08/Kem-Vani-Tra-Sua-Tran-Chau-Hoang-Kim.png', 7, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (42, N'Kem Trà Sữa Trân Châu Hoàng Kim', N'Kem trà sữa với trân châu hoàng kim', 25000, NULL, N'https://tocotocotea.com/wp-content/uploads/2024/08/Kem-Tra-Sua-Tran-Chau-Hoang-Kim.png', 7, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (43, N'Kem Ly Vani Dâu', N'Kem ly vani với dâu tươi', 25000, NULL, N'https://tocotocotea.com/wp-content/uploads/2023/08/z4617754537982_689908f83d0785da485d70d0307e5130.jpg', 7, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (44, N'Cafe Kem Trân Châu Hoàng Kim', N'Cà phê kem với trân châu hoàng kim', 25000, NULL, N'https://tocotocotea.com/wp-content/uploads/2023/05/CF-Kem-Tran-Chau-HK.jpg', 7, 100, 1);
INSERT INTO [dbo].[Products] ([Id], [Name], [Description], [Price], [SalePrice], [Image], [CategoryId], [StockQuantity], [IsPublished]) VALUES (45, N'Kem Trân Châu Hoàng Kim', N'Kem với trân châu hoàng kim đặc biệt', 25000, NULL, N'https://tocotocotea.com/wp-content/uploads/2023/05/kem-tran-chau-hoang-kim.jpg', 7, 100, 1);

SET IDENTITY_INSERT [dbo].[Products] OFF;

GO 